### ISSUE TITLE
{} (frozendict) doesn't work as a TaggedValue

### ISSUE THREAD

**Issue by bitemyapp** [dreid/edn#24]
recording for posterity.

```
...............E.........................................................................................
======================================================================
ERROR: test_tag (edn.tests.test_ast.EDNTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/callen/code/edn/edn/tests/test_ast.py", line 179, in test_tag
    ('#foo {}', TaggedValue(Symbol('foo'), frozendict({})))
  File "/Users/callen/.virtualenv/sweden/lib/python2.7/site-packages/Parsley-1.2-py2.7.egg/terml/nodes.py", line 144, in mkterm
    tuple([coerceToTerm(a) for a in args]),
  File "/Users/callen/.virtualenv/sweden/lib/python2.7/site-packages/Parsley-1.2-py2.7.egg/terml/nodes.py", line 138, in coerceToTerm
    raise ValueError("Could not coerce %r to Term" % (val,))
ValueError: Could not coerce frozendict({}) to Term

----------------------------------------------------------------------
Ran 105 tests in 0.181s

FAILED (errors=1)
```

If I get a workable fix together, I'll PR it with my test(s).

**Comment by jml** [comment]
Thanks. 

I can't see the full code change required to make the test fail in the way described. From the stack trace, though:

``` python
    ('#foo {}', TaggedValue(Symbol('foo'), frozendict({})))
```

This is asserting the wrong thing. At the AST level, `#foo {}` should be transformed into `TaggedValue(Symbol('foo'), Map(()))`.

A more correct test would be to add this to `DecoderTests.test_tagged_value`:

``` python
        self.assertEqual(
            TaggedValue(Symbol('foo', 'qux'), frozendict()),
            from_terms(TaggedValue(Symbol('foo', 'qux'), Map(()))))
```

Which fails with a similar error.

I think the bug here is that `TaggedValue` is doing double duty as an AST token and as a top-level edn object used when we come across a tagged value that has no associated reader.

Note that frozendicts can be read just fine as long as there's a defined reader, e.g.

``` python
    def test_tagged_dict(self):
        readers = {Symbol('foo'): lambda x: x}
        self.assertEqual(frozendict(), loads('#foo {}', readers))
        self.assertEqual(frozendict({1: 2}), loads('#foo {1 2}', readers))
```

It's only when we try constructing a `TaggedValue` with them that they get disruptive. I think the fix is simply to provide a new class for tagged values that don't have readers.

**Comment by bitemyapp** [comment]
@jml it was after mucking about in the libraries (edn, perfidy, and parsley) that I understood the assertions weren't really framed correctly and chucked them out the window. I'm working on tracking down other parse errors as my vendored versions of the libraries don't have Parsley choking on a frozendict anymore.
